global:
  resolve_timeout: 5m

route:
  receiver: "email-receiver"
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "email-receiver"
    email_configs:
      - to: "az0031456@gmail.com"
        from: "az0031456@gmail.com"
        smarthost: 'smtp.gmail.com:587'
        auth_username: "az0031456@gmail.com"
        auth_identity: "az0031456@gmail.com"
        auth_password: "oecoibbxwzbfifom"
