global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-crud"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["app-crud:8084"]

  - job_name: "app-autenticacion"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["app-autenticacion:8087"]

  - job_name: "app-notificaciones"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["app-notificaciones:8085"]

  - job_name: "rabbitmq"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "mongo_database"
    static_configs:
      - targets: ["mongodb_exporter:9216"]  # Monitorea el exportador de MongoDB  

  - job_name: "loki"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "grafana"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["grafana:3000"]

rule_files:
  - '/etc/prometheus/alert.rules.yml'
