openapi: 3.0.3
info:
  title: API Gateway
  description: API Gateway para manejar usuarios y métricas.
  version: 1.0.0
servers:
  - url: http://proyectofinal-api-gateway-1:8075
    description: servidor local de api gateway

paths:
  /api/gateway/usuario/{codigo}:
    delete:
      summary: Eliminar un usuario
      description: Elimina un usuario por código.
      tags:
        - Usuario
      parameters:
        - name: codigo
          in: path
          required: true
          description: Código del usuario
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Usuario eliminado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  respuesta:
                    type: object
        '500':
          description: Error del servidor.

    get:
      summary: Obtener un usuario
      description: Obtiene información de un usuario por código.
      tags:
        - Usuario
      parameters:
        - name: codigo
          in: path
          required: true
          description: Código del usuario
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Información del usuario obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  respuesta:
                    type: object
        '500':
          description: Error del servidor.

    put:
      summary: Actualizar un usuario
      description: Actualiza la información de un usuario por código.
      tags:
        - Usuario
      parameters:
        - name: codigo
          in: path
          required: true
          description: Código del usuario
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                email:
                  type: string
                telefono:
                  type: string
              example:
                nombre: "Juan Pérez"
                email: "juan.perez@example.com"
                telefono: "123456789"
      responses:
        '200':
          description: Usuario actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  respuesta:
                    type: object
        '500':
          description: Error del servidor.

  /api/gateway/usuario/login:
    post:
      summary: Iniciar sesión de usuario
      description: Autentica al usuario usando correo electrónico y contraseña.
      tags:
        - Usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Inicio de sesión exitoso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: false
                  respuesta:
                    type: object
        '500':
          description: Error del servidor.

  /actuator/metrics:
    get:
      summary: Métricas generales
      description: Devuelve métricas generales de la aplicación.
      tags:
        - Métricas
      responses:
        '200':
          description: Métricas obtenidas correctamente.
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Error del servidor.

  /actuator/metrics/{metricname}:
    get:
      summary: Métrica específica
      description: Devuelve la métrica especificada por nombre.
      tags:
        - Métricas
      parameters:
        - name: metricname
          in: path
          required: true
          description: Nombre de la métrica
          schema:
            type: string
      responses:
        '200':
          description: Métrica obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Error del servidor.

  /actuator/metrics/health:
    get:
      summary: Estado de la salud de la aplicación
      description: Devuelve el estado de salud de la aplicación.
      tags:
        - Métricas
      responses:
        '200':
          description: Salud de la aplicación obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Error del servidor.

  /actuator/info:
    get:
      summary: Información de la aplicación
      description: Devuelve información general de la aplicación.
      tags:
        - Métricas
      responses:
        '200':
          description: Información obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Error del servidor.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
